/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace.index'
import { Route as AuthenticatedKnowledgeBaseIndexRouteImport } from './routes/_authenticated/knowledge-base.index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedNoteNoteIdRouteImport } from './routes/_authenticated/note.$noteId'
import { Route as AuthenticatedKnowledgeBaseKnowledgeBaseIdRouteImport } from './routes/_authenticated/knowledge-base.$knowledgeBaseId'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'
import { Route as AuthenticatedmiscAboutRouteImport } from './routes/_authenticated/(misc)/about'
import { Route as AuthenticatedMarketplaceKnowledgeBaseShareSlugRouteImport } from './routes/_authenticated/marketplace.knowledge-base.$shareSlug'
import { Route as AuthenticatedMarketplaceAgentAgentIdRouteImport } from './routes/_authenticated/marketplace.agent.$agentId'
import { Route as AuthenticatedmiscAgentInitialAgentIdRouteImport } from './routes/_authenticated/(misc)/agent-initial.$agentId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKnowledgeBaseIndexRoute =
  AuthenticatedKnowledgeBaseIndexRouteImport.update({
    id: '/knowledge-base/',
    path: '/knowledge-base/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedNoteNoteIdRoute = AuthenticatedNoteNoteIdRouteImport.update({
  id: '/note/$noteId',
  path: '/note/$noteId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute =
  AuthenticatedKnowledgeBaseKnowledgeBaseIdRouteImport.update({
    id: '/knowledge-base/$knowledgeBaseId',
    path: '/knowledge-base/$knowledgeBaseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedmiscAboutRoute = AuthenticatedmiscAboutRouteImport.update({
  id: '/(misc)/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute =
  AuthenticatedMarketplaceKnowledgeBaseShareSlugRouteImport.update({
    id: '/marketplace/knowledge-base/$shareSlug',
    path: '/marketplace/knowledge-base/$shareSlug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceAgentAgentIdRoute =
  AuthenticatedMarketplaceAgentAgentIdRouteImport.update({
    id: '/marketplace/agent/$agentId',
    path: '/marketplace/agent/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedmiscAgentInitialAgentIdRoute =
  AuthenticatedmiscAgentInitialAgentIdRouteImport.update({
    id: '/(misc)/agent-initial/$agentId',
    path: '/agent-initial/$agentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/about': typeof AuthenticatedmiscAboutRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/knowledge-base/$knowledgeBaseId': typeof AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute
  '/note/$noteId': typeof AuthenticatedNoteNoteIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/agent-initial/$agentId': typeof AuthenticatedmiscAgentInitialAgentIdRoute
  '/marketplace/agent/$agentId': typeof AuthenticatedMarketplaceAgentAgentIdRoute
  '/marketplace/knowledge-base/$shareSlug': typeof AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/about': typeof AuthenticatedmiscAboutRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/knowledge-base/$knowledgeBaseId': typeof AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute
  '/note/$noteId': typeof AuthenticatedNoteNoteIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/agent-initial/$agentId': typeof AuthenticatedmiscAgentInitialAgentIdRoute
  '/marketplace/agent/$agentId': typeof AuthenticatedMarketplaceAgentAgentIdRoute
  '/marketplace/knowledge-base/$shareSlug': typeof AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/(misc)/about': typeof AuthenticatedmiscAboutRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/knowledge-base/$knowledgeBaseId': typeof AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute
  '/_authenticated/note/$noteId': typeof AuthenticatedNoteNoteIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/knowledge-base/': typeof AuthenticatedKnowledgeBaseIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/(misc)/agent-initial/$agentId': typeof AuthenticatedmiscAgentInitialAgentIdRoute
  '/_authenticated/marketplace/agent/$agentId': typeof AuthenticatedMarketplaceAgentAgentIdRoute
  '/_authenticated/marketplace/knowledge-base/$shareSlug': typeof AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/about'
    | '/chat/$chatId'
    | '/knowledge-base/$knowledgeBaseId'
    | '/note/$noteId'
    | '/chat/'
    | '/knowledge-base'
    | '/marketplace'
    | '/agent-initial/$agentId'
    | '/marketplace/agent/$agentId'
    | '/marketplace/knowledge-base/$shareSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/about'
    | '/chat/$chatId'
    | '/knowledge-base/$knowledgeBaseId'
    | '/note/$noteId'
    | '/chat'
    | '/knowledge-base'
    | '/marketplace'
    | '/agent-initial/$agentId'
    | '/marketplace/agent/$agentId'
    | '/marketplace/knowledge-base/$shareSlug'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authenticated'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/_authenticated/chat'
    | '/_authenticated/(misc)/about'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/knowledge-base/$knowledgeBaseId'
    | '/_authenticated/note/$noteId'
    | '/_authenticated/chat/'
    | '/_authenticated/knowledge-base/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/(misc)/agent-initial/$agentId'
    | '/_authenticated/marketplace/agent/$agentId'
    | '/_authenticated/marketplace/knowledge-base/$shareSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-base/': {
      id: '/_authenticated/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/note/$noteId': {
      id: '/_authenticated/note/$noteId'
      path: '/note/$noteId'
      fullPath: '/note/$noteId'
      preLoaderRoute: typeof AuthenticatedNoteNoteIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/knowledge-base/$knowledgeBaseId': {
      id: '/_authenticated/knowledge-base/$knowledgeBaseId'
      path: '/knowledge-base/$knowledgeBaseId'
      fullPath: '/knowledge-base/$knowledgeBaseId'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseKnowledgeBaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/(misc)/about': {
      id: '/_authenticated/(misc)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedmiscAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/knowledge-base/$shareSlug': {
      id: '/_authenticated/marketplace/knowledge-base/$shareSlug'
      path: '/marketplace/knowledge-base/$shareSlug'
      fullPath: '/marketplace/knowledge-base/$shareSlug'
      preLoaderRoute: typeof AuthenticatedMarketplaceKnowledgeBaseShareSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/agent/$agentId': {
      id: '/_authenticated/marketplace/agent/$agentId'
      path: '/marketplace/agent/$agentId'
      fullPath: '/marketplace/agent/$agentId'
      preLoaderRoute: typeof AuthenticatedMarketplaceAgentAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/(misc)/agent-initial/$agentId': {
      id: '/_authenticated/(misc)/agent-initial/$agentId'
      path: '/agent-initial/$agentId'
      fullPath: '/agent-initial/$agentId'
      preLoaderRoute: typeof AuthenticatedmiscAgentInitialAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedmiscAboutRoute: typeof AuthenticatedmiscAboutRoute
  AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute: typeof AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute
  AuthenticatedNoteNoteIdRoute: typeof AuthenticatedNoteNoteIdRoute
  AuthenticatedKnowledgeBaseIndexRoute: typeof AuthenticatedKnowledgeBaseIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedmiscAgentInitialAgentIdRoute: typeof AuthenticatedmiscAgentInitialAgentIdRoute
  AuthenticatedMarketplaceAgentAgentIdRoute: typeof AuthenticatedMarketplaceAgentAgentIdRoute
  AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute: typeof AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedmiscAboutRoute: AuthenticatedmiscAboutRoute,
  AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute:
    AuthenticatedKnowledgeBaseKnowledgeBaseIdRoute,
  AuthenticatedNoteNoteIdRoute: AuthenticatedNoteNoteIdRoute,
  AuthenticatedKnowledgeBaseIndexRoute: AuthenticatedKnowledgeBaseIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedmiscAgentInitialAgentIdRoute:
    AuthenticatedmiscAgentInitialAgentIdRoute,
  AuthenticatedMarketplaceAgentAgentIdRoute:
    AuthenticatedMarketplaceAgentAgentIdRoute,
  AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute:
    AuthenticatedMarketplaceKnowledgeBaseShareSlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
